{
 "title": "Model Score",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Model", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Avg. Score in last 10 min",
   "type": "gauge",
   "description": "MIttelerer Sentiment Score",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(fastapi_model_model_score_sum[10m])/increase(fastapi_model_model_score_count[10m])"
    }
   ]
  },
  {
   "title": "Sentiment",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 7, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(fastapi_model_sentiment_total[$__interval])) by (sentiment)",
     "legendFormat": "{{sentiment}}"
    }
   ]
  },
  {
   "title": "Score Distribution",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(fastapi_model_model_score_bucket[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}